# Generated by Django 4.0.3 on 2022-03-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_category_book_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='categories',
            new_name='category',
        ),
    ]
