# Generated by Django 4.0.3 on 2022-03-13 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_remove_book_favorite_book_favorite_user_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
